global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: alloy
    static_configs:
      - targets: ["alloy:12345"]

  - job_name: xaticraft-api
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - "tasks.xc_api"
        type: A
        port: 8080