services:
  api:
    image: rennn0/xaticraft:latest
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      - CERT_DIR=${CERT_DIR}
      - CERT_PATH=${CERT_PATH}
      - CERT_PASS=${CERT_PASS}
    volumes:
      - ./ProtectionKeys:/app/keys
    networks:
      - xc-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: xc-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - xc-network
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      placement:
        constraints:
          - node.labels.db == true

  nginx:
    image: nginx:alpine
    ports:
      - "${INCOMING_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - xc-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 64M

  mongo:
    image: mongodb/mongodb-community-server:8.0-ubi8
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 64M
      placement:
        constraints:
          - node.labels.db == true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/config
    networks:
      - xc-network
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
        
networks:
  xc-network:

volumes:
  pgdata:
  mongo-data:
  mongo-config: