version: '3.8'

services:
  api:
    image: rennn0/xaticraft:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CERT_PATH=/app/certs/xc-dp.pfx
      - CERT_PASS=SAGhJr6c4sVRcIMhrah9Eddp670jXcl2
      - SERVICE_INSTANCE_ID={{.Task.Slot}}
    configs:
      - source: xc_pfx
        target: /app/certs/xc-dp.pfx
    secrets:
      - source: xc_appsettings_prod
        target: appsettings.Production.json
    networks:
      - xc-network
  
  realtime:
    image: rennn0/realtime:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    secrets:
      - source: rt_appsettings_prod
        target: appsettings.Production.json
    networks:
      - xc-network
  
  postgres:
    image: postgres:16
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: xc-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - xc-network
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: [ node.labels.db == true ]

  mongo:
    image: mongodb/mongodb-community-server:8.0-ubi8
    secrets:
      - mongo_user
      - mongo_password
    environment:
      - MONGODB_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_user
      - MONGODB_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - xc-network
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: [ node.labels.db == true ]

  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 8070
        protocol: tcp
        mode: ingress
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    networks:
      - xc-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 64M
  
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=1d"
      - "--web.enable-otlp-receiver"
    volumes:
      - prometheus-data:/prometheus
    configs:
      - source: prometheus_yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - xc-network
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1

networks:
  xc-network:
    driver: overlay

volumes:
  pgdata:
    external: true
    name: xc_pgdata
  mongo-data:
    external: true
    name: xc_mongo-data
  mongo-config:
    external: true
    name: xc_mongo-config
  prometheus-data:
    external: true
    name: xc_prometheus-data

secrets:
  mongo_password:
    external: true
  mongo_user:
    external: true
  postgres_password:
    external: true
  postgres_user:
    external: true
  xc_appsettings_prod:
    external: true
  rt_appsettings_prod:
    external: true

configs:
  xc_pfx:
    external: true
  nginx_conf:
    file: ./nginx.conf
  prometheus_yml:
    file: ./prometheus.yml