version: '3.8'

services:
  api:
    image: rennn0/xaticraft:latest
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      - CERT_PATH=/app/certs/xc-dp.pfx
      - CERT_PASS=SAGhJr6c4sVRcIMhrah9Eddp670jXcl2
    configs:
      - source: xc_pfx
        target: /app/certs/xc-dp.pfx
    networks:
      - xc-network
  
  postgres:
    image: postgres:16
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: xc-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - xc-network
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: [ node.labels.db == true ]

  mongo:
    image: mongodb/mongodb-community-server:8.0-ubi8
    secrets:
      - mongo_user
      - mongo_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/config
    networks:
      - xc-network
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: [ node.labels.db == true ]

  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 8070
        protocol: tcp
        mode: ingress
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    networks:
      - xc-network
    deploy:
      replicas: 1
      #      placement:
      #        constraints:
      #          - node.role == manager
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 64M

networks:
  xc-network:
    driver: overlay

volumes:
  pgdata:
  mongo-data:
  mongo-config:

secrets:
  mongo_password:
    external: true
  mongo_user:
    external: true
  postgres_password:
    external: true
  postgres_user:
    external: true

configs:
  xc_pfx:
    external: true
  nginx_conf:
    file: ./nginx.conf