CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    description text NOT NULL,
    price numeric(10,3) NOT NULL,
    timestamp timestamp without time zone DEFAULT (now()),
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE product_metadata (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    original_file text NOT NULL,
    file_key text NOT NULL,
    location text NOT NULL,
    product_id bigint NOT NULL,
    timestamp timestamp without time zone DEFAULT (now()),
    CONSTRAINT product_metadata_pkey PRIMARY KEY (id),
    CONSTRAINT product_metadata_product_id_fkey FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE INDEX "IX_product_metadata_product_id" ON product_metadata (product_id);


CREATE OR REPLACE VIEW v_products AS
SELECT
    p.id,
    p.title,
    p.description,
    p.price,
    p."timestamp",
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'id', pm.id,
                'original_file', pm.original_file,
                'file_key', pm.file_key,
                'location', pm.location,
                'timestamp', pm."timestamp"
            )
        ) FILTER (WHERE pm.id IS NOT NULL),
        '[]'::jsonb
    ) AS metadata
FROM products p
LEFT JOIN product_metadata pm ON pm.product_id = p.id
GROUP BY p.id;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260205084313_InitalCreate', '8.0.22');

COMMIT;

START TRANSACTION;

CREATE TABLE "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260212141734_ProtectionKeys', '8.0.22');

COMMIT;

