using System.Text.Json.Serialization;

namespace XcLib.Shared.Payment.FlittImpl.Docs;

public record CreateOrderRequestData
{
    /// <summary>
    ///     Protocol version. Default value: 1.0.1 Version 1.0 is deprecated
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; init; } = "1.0.1";

    /// <summary>
    ///     Order ID which is generated by merchant
    /// </summary>
    [JsonPropertyName("order_id")]
    public required string OrderId { get; init; }

    /// <summary>
    ///     Merchant unique ID. Generated by Flitt during merchant registration
    /// </summary>
    [JsonPropertyName("merchant_id")]
    public required int MerchantId { get; init; }

    /// <summary>
    ///     Order description. Generated by merchant in UTF-8 always
    /// </summary>
    [JsonPropertyName("order_desc")]
    public required string OrderDescription { get; init; }

    /// <summary>
    ///     Order amount without separator
    /// </summary>
    [JsonPropertyName("amount")]
    public required int Amount { get; init; }

    /// <summary>
    ///     Order currency
    /// </summary>
    [JsonPropertyName("currency")]
    public required Currency Currency { get; init; }

    /// <summary>
    ///     Merchant site URL, where a customer will be redirected after payment completion
    /// </summary>

    [JsonPropertyName("response_url")]
    public string? ResponseUrl { get; init; }

    /// <summary>
    ///     Merchant site URL, where host-to-host callback will be sent after payment completion. See Callbacks for more
    ///     details on callbacks
    /// </summary>

    [JsonPropertyName("server_callback_url")]
    public string? ServerCallbackUrl { get; init; }

    /// <summary>
    ///     Order signature. Required to verify merchant request consistency and authenticity. Signature generation algorithm
    ///     please see at Signature generation for request and response
    /// </summary>
    [JsonPropertyName("signature")]
    public string? Signature { get; set; }

    /// <summary>
    ///     Order lifetime in seconds. After this period of time, the order will change status to ‘expired’ if the client has
    ///     not paid it
    ///     Default value: 36000
    ///     Maximum allowed value: 69120000
    /// </summary>

    [JsonPropertyName("lifetime")]
    public int? Lifetime { get; init; }

    /// <summary>
    ///     Any arbitrary set of data that a merchant wants to get back in the response to response_url or/and
    ///     server_callback_url, and also in reports
    /// </summary>

    [JsonPropertyName("merchant_data")]
    public string? MerchantData { get; init; }

    /// <summary>
    ///     Parameter supported only for Visa/MasterCard payment method
    ///     N — the amount is debited from the customer’s card immediately and settled to the merchant account, in accordance
    ///     with the rules of settlements.
    ///     Y — amount is held on the customer card account and not charged until the merchant sends a capture request to
    ///     confirm.
    ///     Default value: N
    /// </summary>

    [JsonPropertyName("preauth")]
    public Checkbox? Preauth { get; init; }

    /// <summary>
    ///     Customer email
    /// </summary>

    [JsonPropertyName("sender_email")]
    public string? SenderEmail { get; init; }

    /// <summary>
    ///     Delayed order flag.
    ///     Y — allows the customer to pay the order during period sent by the merchant in lifetime parameter. Merchant must
    ///     expect several host-to-host callbacks and browser redirects at the same order. Customer will have the possibility
    ///     to try to pay the same order_id, if the previous attempt failed
    ///     N — after payment is declined order_id customer will be redirected to the merchant site to recreate the order. In
    ///     this case, only one callback will be sent to server_callback_url
    ///     Default value: Y
    /// </summary>

    [JsonPropertyName("delayed")]
    public Checkbox? Delayed { get; init; }

    /// <summary>
    ///     Payment page language.
    /// </summary>

    [JsonPropertyName("lang")]
    public Language? Language { get; init; }

    /// <summary>
    ///     Merchant product or service id
    /// </summary>

    [JsonPropertyName("product_id")]
    public string? ProductId { get; init; }

    /// <summary>
    ///     Flag which indicates whether card token will be returned in response. See Recuring payment
    ///     Default value: N
    /// </summary>
    [JsonPropertyName("required_rectoken")]
    public Checkbox? RequiredRectoken { get; init; }

    /// <summary>
    ///     If Y sent, order will be automatically reversed after successful approval
    ///     Default value: N
    /// </summary>

    [JsonPropertyName("verification")]
    public Checkbox? Verification { get; init; }

    /// <summary>
    ///     Card token for recurring transactions.
    /// </summary>

    [JsonPropertyName("rectoken")]
    public string? Rectoken { get; init; }

    /// <summary>
    ///     Card token for payout transactions.
    /// </summary>
    [JsonPropertyName("receiver_rectoken")]
    public string? ReceiverRectoken { get; init; }

    /// <summary>
    ///     ID of checkout design which is set in merchant portal
    /// </summary>

    [JsonPropertyName("design_id")]
    public string? DesignId { get; init; }

    /// <summary>
    ///     Y – enable scheduled payments
    ///     N – by default, disable scheduled payments
    /// </summary>

    [JsonPropertyName("subscription")]
    public Checkbox? Subscription { get; init; }

    /// <summary>
    ///     Merchant site URL, where host-to-host callback will be sent after scheduled payment completion
    /// </summary>

    [JsonPropertyName("subscription_callback_url")]
    public string? SubscriptionCallbackUrl { get; init; }

    /// <summary>
    ///     Url for chargeback callbacks
    /// </summary>
    [JsonPropertyName("chargeback_callback_url")]
    public string? ChargebackCallbackUrl { get; init; }

    /// <summary>
    ///     The URL, where customer will be redirected if clicks "Cancel" button on checkout page
    /// </summary>

    [JsonPropertyName("cancel_url")]
    public string? CancelUrl { get; init; }

    /// <summary>
    ///     BASE64 encoded JSON data, refer to Additional Data details page
    /// </summary>

    [JsonPropertyName("reservation_data")]
    public string? ReservationData { get; init; }
}