using System.Text.Json.Serialization;

namespace XcLib.Shared.Payment.FlittImpl.Docs;

public record GetOrderStatusRequestData
{
    /// <summary>
    ///     Protocol version. Default value: 1.0.1 Version 1.0 is deprecated
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; init; } = "1.0.1";

    /// <summary>
    ///     Order ID which is generated by merchant
    /// </summary>
    [JsonPropertyName("order_id")]
    public required string OrderId { get; init; }

    /// <summary>
    ///     Merchant unique ID. Generated by Flitt during merchant registration
    /// </summary>
    [JsonPropertyName("merchant_id")]
    public required int MerchantId { get; init; }

    /// <summary>
    ///     Order signature. Required to verify merchant request consistency and authenticity. Signature generation algorithm
    ///     please see at Signature generation for request and response
    /// </summary>
    [JsonPropertyName("signature")]
    public string? Signature { get; set; }
}