using System.Text.Json.Serialization;

namespace XcLib.Shared.Payment.FlittImpl.Docs;

public record GetOrderStatusResponseData
{
    /// <summary>
    ///     Order ID which is generated by merchant.
    /// </summary>
    [JsonPropertyName("order_id")] public required string OrderId { get; init; }

    /// <summary>
    ///     Merchant unique ID. Generated by Flitt during merchant registration.
    /// </summary>

    [JsonPropertyName("merchant_id")] public long MerchantId { get; init; }

    /// <summary>
    ///     Order amount in cents without separator
    /// </summary>

    [JsonPropertyName("amount")] public string? Amount { get; init; }

    /// <summary>
    ///     Order currency. Supported values: see Currencies
    /// </summary>

    [JsonPropertyName("currency")]
    public string? Currency { get; init; }

    [JsonIgnore] public Currency? CurrencyEnum => Enum.TryParse(Currency, true, out Currency c) ? c : null;

    /// <summary>
    ///     Order processing status. Can contain the following values:
    ///     created — order has been created, but the customer has not entered payment details yet; merchant must continue to
    ///     request the status of the order
    ///     processing — order is still in processing by payment gateway; merchant must continue to request the status of the
    ///     order
    ///     declined — order is declined by Flitt payment gateway or by a bank or by an external payment system
    ///     approved — order completed successfully, funds are held on the payer’s account and soon will be credited of the
    ///     merchant; merchant can provide the service or ship goods
    ///     expired — order lifetime expired.
    ///     reversed — previously approved transaction was fully reversed. In this case, parameter reversal_amount will be
    ///     equal to actual_amount
    /// </summary>
    [JsonPropertyName("order_status")]
    public string? OrderStatus { get; init; }

    [JsonIgnore]
    public FlittOrderStatus? OrderStatusEnum =>
        Enum.TryParse(OrderStatus, true, out FlittOrderStatus v) ? v : null;

    /// <summary>
    ///     Request processing status. If parameters sent by merchant did not pass validation then failure, else success
    /// </summary>

    [JsonPropertyName("response_status")]
    public string? ResponseStatus { get; init; }

    [JsonIgnore]
    public ResponseStatus? ResponseStatusEnum => Enum.TryParse(ResponseStatus, true, out ResponseStatus v) ? v : null;

    /// <summary>
    ///     Order signature. Required to verify merchant request consistency and authenticity. Signature generation algorithm
    ///     please see at Signature generation for request and response and response
    /// </summary>

    [JsonPropertyName("signature")] public string? Signature { get; init; }

    /// <summary>
    ///     Supported values:
    ///     purchase
    ///     verification
    ///     p2p credit
    ///     p2p transfer
    ///     settlement — split payments
    ///     reverse
    /// </summary>

    [JsonPropertyName("tran_type")]
    public string? TranType { get; init; }

    [JsonIgnore]
    public TransactionType? TranTypeEnum => Enum.TryParse(TranType, true, out TransactionType v) ? v : null;

    /// <summary>
    ///     Commonly not unique transaction ID returned by bank.
    /// </summary>

    [JsonPropertyName("rrn")] public string? Rrn { get; init; }

    /// <summary>
    ///     Masked card number
    /// </summary>
    [JsonPropertyName("masked_card")] public string? MaskedCard { get; init; }

    /// <summary>
    ///     Customer mobile phone number
    /// </summary>
    [JsonPropertyName("sender_cell_phone")]
    public string? SenderCellPhone { get; init; }

    /// <summary>
    ///     Customer payment account
    /// </summary>
    [JsonPropertyName("sender_account")] public string? SenderAccount { get; init; }

    /// <summary>
    ///     Card bin — usually first 6 digits 444444r
    /// </summary>

    [JsonPropertyName("card_bin")]
    public object? CardBin { get; init; }

    /// <summary>
    ///     Supported values:
    ///     VISA, MasterCard, Humo, UzCard
    /// </summary>

    [JsonPropertyName("card_type")] public string? CardType { get; init; }

    /// <summary>
    ///     Commonly not unique authorization code returned by bank.
    /// </summary>

    [JsonPropertyName("approval_code")] public string? ApprovalCode { get; init; }

    /// <summary>
    ///     Order decline response code. Possible codes see in Response codes
    /// </summary>

    [JsonPropertyName("response_code")] public object? ResponseCode { get; init; }

    /// <summary>
    ///     Order response code description, see Response codes
    /// </summary>

    [JsonPropertyName("response_description")]
    public string? ResponseDescription { get; init; }

    /// <summary>
    ///     The total amount of all reversals for current order
    /// </summary>

    [JsonPropertyName("reversal_amount")] public string? ReversalAmount { get; init; }

    /// <summary>
    ///     The settlement amount for current order
    /// </summary>

    [JsonPropertyName("settlement_amount")]
    public string? SettlementAmount { get; init; }

    /// <summary>
    ///     The currency of order settlement
    /// </summary>

    [JsonPropertyName("settlement_currency")]
    public string? SettlementCurrency { get; init; }

    [JsonIgnore]
    public Currency? SettlementCurrencyEnum =>
        Enum.TryParse(SettlementCurrency, true, out Currency c)
            ? c
            : null;

    /// <summary>
    ///     Order creation date DD.MM.YYYY hh:mm:ss
    /// </summary>

    [JsonPropertyName("order_time")] public string? OrderTime { get; init; }

    /// <summary>
    ///     Settlement date in format DD.MM.YYYY
    /// </summary>

    [JsonPropertyName("settlement_date")] public string? SettlementDate { get; init; }

    /// <summary>
    ///     Ecommerce Indicator – parameter specifies whether 3DSecure authentication was performed or not. Supported values:
    ///     5 — full 3DSecure authentication performed
    ///     6 — merchant supports 3DSecure, but issuing bank does not
    ///     7 — neither merchant nor issuing bank supports 3DSecure
    /// </summary>

    [JsonPropertyName("eci")] public string? Eci { get; init; }

    /// <summary>
    ///     Fee charged by Flitt
    /// </summary>

    [JsonPropertyName("fee")] public string? Fee { get; init; }

    /// <summary>
    ///     Payment system which was used for payment. Supported payment systems list see Supported payment systems
    /// </summary>

    [JsonPropertyName("payment_system")] public string? PaymentSystem { get; init; }

    /// <summary>
    ///     Customer email
    /// </summary>

    [JsonPropertyName("sender_email")] public string? SenderEmail { get; init; }

    /// <summary>
    ///     Unique payment ID generated by Flitt payment gateway
    /// </summary>

    [JsonPropertyName("payment_id")] public long? PaymentId { get; init; }

    /// <summary>
    ///     The actual amount held or charged from card.
    /// </summary>

    [JsonPropertyName("actual_amount")] public string? ActualAmount { get; init; }

    /// <summary>
    ///     The actual currency authorized from card
    /// </summary>

    [JsonPropertyName("actual_currency")] public string? ActualCurrency { get; init; }

    [JsonIgnore] public Currency? ActualCurrencyEnum => Enum.TryParse(ActualCurrency, true, out Currency c) ? c : null;

    /// <summary>
    ///     Merchant product or service ID
    /// </summary>

    [JsonPropertyName("product_id")] public string? ProductId { get; init; }

    /// <summary>
    ///     Any arbitrary set of data that a merchant sends in a request
    /// </summary>

    [JsonPropertyName("merchant_data")] public string? MerchantData { get; init; }

    /// <summary>
    ///     Code verification result.
    ///     Supported values:
    ///     verified — card successfully verified with code
    ///     incorrect — incorrect code entered but limit not exceeded yet
    ///     failed — allowed number of invalid attempts to enter code exceeded
    ///     created — verification code created but not entered yet
    /// </summary>
    [JsonPropertyName("verification_status")]
    public string? VerificationStatus { get; init; }

    [JsonIgnore]
    public VerificationStatus? VerificationStatusEnum =>
        Enum.TryParse(VerificationStatus, true, out VerificationStatus v) ? v : null;

    /// <summary>
    ///     Flag which indicates whether Flitt must return card token — token to access card funds without cardholder
    ///     interaction
    /// </summary>

    [JsonPropertyName("rectoken")] public string? Rectoken { get; init; }

    /// <summary>
    ///     Token lifetime in format DD.MM.YYYY hh:mm:ss
    /// </summary>
    [JsonPropertyName("rectoken_lifetime")]
    public string? RectokenLifetime { get; init; }

    /// <summary>
    ///     Additional field in JSON format
    ///     {
    ///     "bank_name": "Some bank in US country",
    ///     "bank_country": "US",
    ///     "bank_response_code": "decln_1000",
    ///     "card_product": "DEBIT",
    ///     "card_category": "CLASSIC",
    ///     "settlement_fee": 0.2,
    ///     "capture_status": "captured",
    ///     "client_fee": 0.3,
    ///     "ipaddress_v4": "8.8.8.8",
    ///     "capture_amount": 200,
    ///     "card_type": "VISA",
    ///     "reservation_data": null,
    ///     "bank_response_description": "General decline",
    ///     "transaction_id": 1058755083,
    ///     "timeend":"10.01.2018 11:21:30",
    ///     "payment_method": "apple" or "googlepay" or "card",
    ///     "schemeid":"M11111111111111",
    ///     "masked_iban":"GE40XB**8712"
    ///     }
    /// </summary>
    [JsonPropertyName("additional_info")]
    public string? AdditionalInfoRaw { get; init; }
    
    [JsonPropertyName("fee_oplata")] public string? FeeOplata { get; init; }

    [JsonPropertyName("parent_order_id")] public string? ParentOrderId { get; init; }

    [JsonPropertyName("response_signature_string")] public string? SignatureStringRaw { get; init; }
}