name: Build and Push Images

on:
  push:
    branches: ["master"]

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  xaticraft:
    name: Build & Push XatiCraft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: rennn0
          password: ${{ secrets.DOKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push XatiCraft
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./XatiCraft/Dockerfile
          push: true
          cache-from: type=gha,scope=xaticraft
          cache-to: type=gha,mode=max,scope=xaticraft
          tags: rennn0/xaticraft:latest


  realtime:
    name: Build & Push Realtime
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: rennn0
          password: ${{ secrets.DOKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Realtime
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Realtime/Dockerfile
          push: true
          cache-from: type=gha,scope=realtime
          cache-to: type=gha,mode=max,scope=realtime
          tags: rennn0/realtime:latest